name = "fastmcp-basic-example"
main = "index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Optional: Configure custom domain
# routes = [
#   { pattern = "mcp.yourdomain.com/*", zone_name = "yourdomain.com" }
# ]

# Environment variables (optional)
[vars]
ENVIRONMENT = "development"
LOG_LEVEL = "info"

# Production environment configuration
[env.production]
name = "fastmcp-basic-production"
vars = { ENVIRONMENT = "production", LOG_LEVEL = "warn" }

# KV namespace bindings (if needed)
# [[kv_namespaces]]
# binding = "MCP_DATA"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# D1 database bindings (if needed)
# [[d1_databases]]
# binding = "DB"
# database_name = "mcp-database"
# database_id = "your-database-id"

# R2 bucket bindings (if needed)
# [[r2_buckets]]
# binding = "BUCKET"
# bucket_name = "mcp-storage"

# Durable Object bindings (if needed)
# [[durable_objects.bindings]]
# name = "MCP_SESSION"
# class_name = "MCPSession"

# Workers Analytics Engine (if needed)
# [[analytics_engine_datasets]]
# binding = "MCP_ANALYTICS"